In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv("S1AIW_S2AL2A_DEM_IDX_SOCS_SG_300m.csv")

In [31]:
df

,fid,id,left,top,right,bottom,VH_1,VV_1,BAND_2,BAND_3,...,SG_15_30,SG_5_15,OC,DEM_CS,DEM_LSF,DEM_TWI,DEM_ELEV,EVI,NDVI,SATVI
0,1,1,293261.8479,652590.5522,293561.8479,652890.5522,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,293261.8479,652290.5522,293561.8479,652590.5522,0.042028,0.140731,75.0,271.0,...,917.0,1230.0,100.0,0.024248,0.0,16.852356,234.240005,0.846895,0.902686,-144.214447
2,3,3,293261.8479,651990.5522,293561.8479,652290.5522,0.042028,0.140731,174.0,474.0,...,838.0,1124.0,102.0,0.024248,0.0,16.852356,234.240005,0.769689,0.835903,-359.750702
3,4,4,293261.8479,651690.5522,293561.8479,651990.5522,0.036185,0.094639,30.0,231.0,...,772.0,953.0,103.0,0.024533,0.0,16.879290,227.399994,0.800891,0.910401,-121.167633
4,5,5,293261.8479,651390.5522,293561.8479,651690.5522,0.040302,0.124519,272.0,735.0,...,838.0,1010.0,102.0,0.019689,0.0,17.142696,223.000000,0.686263,0.771026,-680.176636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25278,25279,25279,350861.8479,614790.5522,351161.8479,615090.5522,0.029614,0.054618,286.0,697.0,...,511.0,733.0,83.0,0.068024,0.0,16.985582,106.016441,0.773373,0.798949,-633.630737
25279,25280,25280,350861.8479,614490.5522,351161.8479,614790.5522,0.014342,0.059826,279.0,684.0,...,438.0,659.0,83.0,0.122049,0.0,16.190401,139.048859,0.902216,0.844150,-577.049500
25280,25281,25281,350861.8479,614190.5522,351161.8479,614490.5522,0.015620,0.048791,249.0,704.0,...,623.0,662.0,78.0,0.145789,0.0,15.466097,159.352585,0.886131,0.857173,-590.516174
25281,25282,25282,350861.8479,613890.5522,351161.8479,614190.5522,0.022549,0.060471,113.0,332.0,...,702.0,625.0,90.0,0.100231,0.0,15.314701,174.600281,0.871693,0.867723,-295.480286
25282,25283,25283,350861.8479,613590.5522,351161.8479,613890.5522,0.016006,0.077701,239.0,698.0,...,718.0,554.0,92.0,0.071292,0.0,15.324566,194.779892,0.916469,0.889721,-619.946350

In [32]:
df.fillna(0.0, inplace=True)
df.replace(0, 1, inplace=True)

In [33]:
df

,fid,id,left,top,right,bottom,VH_1,VV_1,BAND_2,BAND_3,...,SG_15_30,SG_5_15,OC,DEM_CS,DEM_LSF,DEM_TWI,DEM_ELEV,EVI,NDVI,SATVI
0,1,1,293261.8479,652590.5522,293561.8479,652890.5522,1.000000,1.000000,1.0,1.0,...,1.0,1.0,1.0,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000
1,2,2,293261.8479,652290.5522,293561.8479,652590.5522,0.042028,0.140731,75.0,271.0,...,917.0,1230.0,100.0,0.024248,1.0,16.852356,234.240005,0.846895,0.902686,-144.214447
2,3,3,293261.8479,651990.5522,293561.8479,652290.5522,0.042028,0.140731,174.0,474.0,...,838.0,1124.0,102.0,0.024248,1.0,16.852356,234.240005,0.769689,0.835903,-359.750702
3,4,4,293261.8479,651690.5522,293561.8479,651990.5522,0.036185,0.094639,30.0,231.0,...,772.0,953.0,103.0,0.024533,1.0,16.879290,227.399994,0.800891,0.910401,-121.167633
4,5,5,293261.8479,651390.5522,293561.8479,651690.5522,0.040302,0.124519,272.0,735.0,...,838.0,1010.0,102.0,0.019689,1.0,17.142696,223.000000,0.686263,0.771026,-680.176636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25278,25279,25279,350861.8479,614790.5522,351161.8479,615090.5522,0.029614,0.054618,286.0,697.0,...,511.0,733.0,83.0,0.068024,1.0,16.985582,106.016441,0.773373,0.798949,-633.630737
25279,25280,25280,350861.8479,614490.5522,351161.8479,614790.5522,0.014342,0.059826,279.0,684.0,...,438.0,659.0,83.0,0.122049,1.0,16.190401,139.048859,0.902216,0.844150,-577.049500
25280,25281,25281,350861.8479,614190.5522,351161.8479,614490.5522,0.015620,0.048791,249.0,704.0,...,623.0,662.0,78.0,0.145789,1.0,15.466097,159.352585,0.886131,0.857173,-590.516174
25281,25282,25282,350861.8479,613890.5522,351161.8479,614190.5522,0.022549,0.060471,113.0,332.0,...,702.0,625.0,90.0,0.100231,1.0,15.314701,174.600281,0.871693,0.867723,-295.480286
25282,25283,25283,350861.8479,613590.5522,351161.8479,613890.5522,0.016006,0.077701,239.0,698.0,...,718.0,554.0,92.0,0.071292,1.0,15.324566,194.779892,0.916469,0.889721,-619.946350

In [35]:
df.to_csv("S1AIW_S2AL2A_DEM_IDX_SOCS_SG_300m_processed.csv")